### PR TITLE
Conda build prepare

### PR DESCRIPTION
**Pull request by PiotrZierhoffer**
This PR makes use of conda-build-prepare

### CODE REVIEW

**Comment by PiotrZierhoffer** [comment]
The conflict is there as we need to add `litex-hub/label/travis-$branch-$TRAVIS_BUILD_ID` as a temp channel - not a big issue

**Comment by mithro** [comment]
Conflicts?

**Comment by PiotrZierhoffer** [comment]
As i commented above, should be easily fixable , just need to find a moment for that

**Comment by ajelinski** [comment]
All CIs green:
* https://travis-ci.com/github/litex-hub/litex-conda-misc/builds/205697261
* https://travis-ci.com/github/litex-hub/litex-conda-prog/builds/205697033
* https://travis-ci.com/github/litex-hub/litex-conda-compilers/builds/205697501
* https://travis-ci.com/github/litex-hub/litex-conda-eda/builds/205869144

**Comment by PiotrZierhoffer** [comment]
We are green on all repos, let's merge

**Pull request merged**
